baseURL = 'https://headandnecksurgery.co.nz/'
languageCode = 'en-us'
title = 'Dr Benjamin Chan'
theme = "benchan"

pagination.pagerSize = 20

[params]
    legal_title = "Benjamin Chan"

    # Meta ------------
    description = "Dr Benjamin Chan, Head and Neck Surgeon based in Auckland, New Zealand"
    keywords = "Dr Benjamin Chan, Head and Neck Surgeon, Head and Neck cancer, Oral cavity, throat, sinonasal, Neck lumps, Skin cancers, Salivary gland disorders, Difficulty swallowing, Altered voice, Thyroid, Nodules, Goitre, Thyroid cancer, Hyperthyroidism, Thyroglossal duct cysts, Hyperparathyroidism, Nose and Sinus, Blocked nose, Bleeding nose, Deviated septum, Nasal polyps, Sinusitis, Rhinitis, Paediatric ENT, Snoring/sleep disordered breathing, Enlarged tonsils, Glue ear, Ear infections, Tonsillitis, Neck lumps, Auckland"

    # Global settings ------------
    favicon_32 = "/imgs/favicon-32x32.png"
    favicon_16 = "/imgs/favicon-16x16.png"
    
    dateformat = "January 2, 2006"
    
    # layout settings ------------
    headerLayout = "left" # options: left, center, right
    footerLayout = "left" # options: left
    footerNewsletter = true

    # Blog ------------ 
    author = "Dr Benjamin Chan"
    info = "Head and Neck Surgeon"

    # analytics
    google_analitycs_id = 'G-8QHDY3JWQT'
    
[taxonomies]
    category = "categories"
    tag = "tags"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# Menus
# -------------------------------------
# header
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Services"
    weight = 2
    url = "/services"
[[menu.main]]
    name = "Contact"
    weight = 3
    url  = "/contact"


# Footer (these add onto the header menu)
# [[menu.footer]]
#     name = "Terms and Conditions"
#     weight = 1
#     url  = "/terms-and-conditions"
[[menu.footer]]
    name = "Privacy policy"
    weight = 1
    url  = "/privacy-policy"


# Social panel (leave empty to hide)
[[menu.social]]
    name = "fab fa-instagram"
    weight = 1
    url  = ""
[[menu.social]]
    name = "lni lni-facebook-original"
    weight = 2
    url  = ""
[[menu.social]]
    name = "fab fa-twitter"
    weight = 3
    url  = "asd"
[[menu.social]]
    name = "fab fa-tiktok"
    weight = 4
    url  = "ticktok"
[[menu.social]]
    name = "fab fa-youtube"
    weight = 5
    url  = "youtube"
[[menu.social]]
    name = "fab fa-linkedin-in"
    weight = 6
    url  = "asd"
[[menu.social]]
    name = "lni lni-envelope"
    weight = 7
    url  = "admin@headandnecksurgery.co.nz"


    